package downloader

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func normalizeLangCode(code string) string {
	c := strings.ToLower(strings.TrimSpace(code))
	if c == "" {
		return ""
	}
	if i := strings.Index(c, "-"); i > 0 {
		return c[:i]
	}
	if i := strings.Index(c, "_"); i > 0 {
		return c[:i]
	}
	return c
}

func isOriginalLang(code, videoLang string) bool {
	code = strings.ToLower(strings.TrimSpace(code))
	videoLang = strings.ToLower(strings.TrimSpace(videoLang))
	if code == "" || videoLang == "" {
		return false
	}
	if code == videoLang {
		return true
	}
	return normalizeLangCode(code) == normalizeLangCode(videoLang)
}

func GetAvailableSubtitles(ytdlp, url string) ([]SubOption, error) {
	cmd := exec.Command(ytdlp,
		"--print", "%(subtitles)j",
		"--print", "%(automatic_captions)j",
		"--print", "%(language)s",
		"--encoding", "utf-8",
		"--no-warnings",
		"--skip-download",
		"--no-playlist",
		url,
	)
	cmd.Env = append(os.Environ(), "PYTHONIOENCODING=utf-8")

	setCmdHideWindow(cmd)

	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	if len(lines) < 3 {
		if len(lines) < 2 {
			return nil, fmt.Errorf("failed to parse subtitle data")
		}
	}

	var manualMap map[string]interface{}
	var autoMap map[string]interface{}
	videoLang := "en"

	json.Unmarshal([]byte(lines[0]), &manualMap)
	json.Unmarshal([]byte(lines[1]), &autoMap)
	if len(lines) >= 3 {
		videoLang = strings.TrimSpace(lines[2])
		if videoLang == "NA" || videoLang == "" {
			videoLang = "en"
		}
	}

	var options []SubOption
	var creatorCodes []string
	for code := range manualMap {
		creatorCodes = append(creatorCodes, code)
	}
	sort.Strings(creatorCodes)
	for _, code := range creatorCodes {
		options = append(options, SubOption{
			Label:      fmt.Sprintf("Creator (Uploaded Subtitle - %s)", code),
			Code:       code,
			IsAuto:     false,
			IsOriginal: isOriginalLang(code, videoLang),
		})
	}

	var autoCodes []string
	for code := range autoMap {
		autoCodes = append(autoCodes, code)
	}
	sort.Strings(autoCodes)
	for _, code := range autoCodes {
		label := fmt.Sprintf("Autogenerated (%s)", code)
		if isOriginalLang(code, videoLang) {
			label = fmt.Sprintf("Autogenerated (Original - %s)", code)
		}
		options = append(options, SubOption{
			Label:      label,
			Code:       code,
			IsAuto:     true,
			IsOriginal: isOriginalLang(code, videoLang),
		})
	}

	// Some videos expose translatable auto-captions without explicit language keys.
	if len(options) == 0 && len(autoMap) > 0 {
		options = append(options, SubOption{
			Label:      "Autogenerated (en)",
			Code:       "en",
			IsAuto:     true,
			IsOriginal: normalizeLangCode(videoLang) == "en",
		})
	}

	return options, nil
}
